---

- name: Install netdata on a Linux host
  hosts: ZABBIX-PRD
  remote_user: root
  become: true
  tasks:
    - name: Install depdendencies
      yum:
        name: "{{item}}"
        state: present
      with_items:
        - zlib-devel
        - libuuid-devel
        - libmnl-devel
        - gcc
        - make
        - git
        - autoconf
        - autogen
        - automake
        - pkgconfig

    - name: Download and extract netdata
      unarchive:
        src: https://github.com/firehol/netdata/releases/download/v1.2.0/netdata-1.2.0.tar.gz
        dest: /tmp/
        copy: no
        creates: /tmp/netdata-1.2.0

    - name: Install netdata
      shell: cd /tmp/netdata-1.2.0; ./netdata-installer.sh 

    - name: Move the systemd file in place
      copy:
        remote_src: true
        src: /tmp/netdata-1.2.0/system/netdata-init-d
        dest: /etc/init.d/netdata 
        mode: 0770

    - name: Start the service
      service:
        name: netdata
        state: started
        enabled: true
