---
- hosts: ZABBIX-PRD
  remote_user: root
  vars:
    zabbix_server: "10.1.235.92"

  tasks:
  - name: Install Zabbix Repository and other packages needed by Ansible
    yum: pkg={{item}} state=installed  
    with_items:
       - https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm

  - name: Installing the Zabbix Agent
    yum: name=zabbix-agent

  - lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^LogFileSize=0'
      line: 'LogFileSize=256'

  - lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^# EnableRemoteCommands=0'
      line: 'EnableRemoteCommands=1'

  - lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^Server=127.0.0.1'
      line: 'Server={{ zabbix_server }}'

  - lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^ServerActive=127.0.0.1'
      line: 'ServerActive={{ zabbix_server }}'

  - lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^Hostname=Zabbix server'
      line: 'Hostname={{ ansible_hostname }}'

  - lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^# HostMetadata='
      line: 'HostMetadata=DC_LINUX'

  - lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^# Timeout=3'
      line: 'Timeout=10'

  - name: Starting the Zabbix Agent
    service: name=zabbix-agent state=started enabled=yes
